
export enum AppEvent {
    USER_LOGIN = 'USER_LOGIN',
    USER_LOGOUT = 'USER_LOGOUT',
    TRANSFER_STARTED = 'TRANSFER_STARTED',
    TRANSFER_COMPLETED = 'TRANSFER_COMPLETED',
    TRANSFER_FAILED = 'TRANSFER_FAILED',
    PLAYLIST_CREATED = 'PLAYLIST_CREATED',
    PLAYLIST_DELETED = 'PLAYLIST_DELETED',
    SONG_ADDED = 'SONG_ADDED',
    SONG_REMOVED = 'SONG_REMOVED',
    ERROR_OCCURRED = 'ERROR_OCCURRED'
}